In [13]:
import numpy as np

In [14]:
def f(v, w, vbar, wbar, l):
    return 0.5*(v - vbar)**2 + 0.5*np.linalg.norm(w - wbar)**2 + l*v*np.sum(w)

In [15]:
def grad_f(v, w, vbar, wbar, l):
    grad_v = v - vbar + l*np.sum(w)
    grad_w = w - wbar + l*v
    return grad_v, grad_w

In [16]:
def GD(vbar, wbar, l, n=100, alpha=0.01):
    v = 0
    w = np.zeros(len(wbar))
    for i in range(n):
        grad_v, grad_w = grad_f(v, w, vbar, wbar, l)
        v = np.max([v - alpha*grad_v, np.zeros(len(vbar))], axis=0)
        w = np.max([w - alpha*grad_w, np.zeros(len(wbar))], axis=0)
    return v, w

In [17]:
m = 10

vbar = 0.01
#wbar = np.array([0.1,0.2,0.3,0.4,0.5,0.6])
wbar = np.sort(np.random.rand(100))

In [18]:
#v, w = GD(vbar, wbar, l, n=1000, alpha=0.1)
#print(v)
#print(w)
#print(f(v,w,vbar,wbar,l))

In [19]:
l = 0.1
vbar = 1
sbar = min(int(1 + 1/l**2), len(wbar))
fs = []
vs = []
print(f(vbar,0,vbar,wbar,l))
for s in range(1, sbar+1):
    #if vbar - l * np.sum(wbar[-s:]) <= 0:
    #    v = 0
    #    w = wbar
    #else:
    v = 1 / (1 - l**2 * s) * (vbar - l * np.sum(wbar[-s:]))
    #print(v)
    w = np.zeros(len(wbar))
    w[-s:] = wbar[-s:] - l*v
    #print(w)
    if not ((w >= 0).all() and v >= 0):
        print("infeasible")
    vs.append(v)
    fs.append(f(v,w,vbar,wbar,l))
    print("s = {}, 1-l^2s = {}, hs= {}".format(s, 1-l**2*s, f(v,w,vbar,wbar,l)))

20.769555940445557
s = 1, 1-l^2s = 0.99, hs= 20.369764669188203
s = 2, 1-l^2s = 0.98, hs= 19.963723457928843
s = 3, 1-l^2s = 0.97, hs= 19.549423179100028
s = 4, 1-l^2s = 0.96, hs= 19.139168038661875
s = 5, 1-l^2s = 0.95, hs= 18.72805615700743
s = 6, 1-l^2s = 0.94, hs= 18.317969179468026
s = 7, 1-l^2s = 0.9299999999999999, hs= 17.90274244044222
s = 8, 1-l^2s = 0.9199999999999999, hs= 17.482976456136875
s = 9, 1-l^2s = 0.9099999999999999, hs= 17.06200480749879
s = 10, 1-l^2s = 0.9, hs= 16.634541801719084
infeasible
s = 11, 1-l^2s = 0.89, hs= 16.21360197024378
infeasible
s = 12, 1-l^2s = 0.88, hs= 15.787386758018764
infeasible
s = 13, 1-l^2s = 0.87, hs= 15.354128953808221
infeasible
s = 14, 1-l^2s = 0.86, hs= 14.915365140471993
infeasible
s = 15, 1-l^2s = 0.85, hs= 14.473007471472034
infeasible
s = 16, 1-l^2s = 0.84, hs= 14.027518192721148
infeasible
s = 17, 1-l^2s = 0.83, hs= 13.574750776377307
infeasible
s = 18, 1-l^2s = 0.82, hs= 13.113841269813848
infeasible
s = 19, 1-l^2s = 0.8099999

## Fast prox single output

In [105]:
l = 0.1
vbar = 1
v_s = 1/(1-l**2*np.arange(1,len(wbar)+1)) * (vbar - l*np.cumsum(wbar[::-1]))
s = min(min(np.where(vbar - l*np.cumsum(wbar[::-1]) > 0)[0][-1]+1, np.where(wbar[::-1] - l*v_s > 0)[0][-1]+1), int(1 + 1/l**2))
if s == 0:
    v = vbar
    w = np.zeros(len(wbar))
else:
    v = 1 / (1 - l**2 * s) * (vbar - l * np.sum(wbar[-s:]))
    w = np.zeros(len(wbar))
    w[-s:] = wbar[-s:] - l*v
f(v,w,vbar,wbar,l)

16.707894399057615

In [106]:
s

10

In [108]:
w

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.     

In [94]:
w

array([0.      , 0.      , 0.084375, 0.184375, 0.284375, 0.384375])

In [74]:

[-1/(2*(1-l**2*s)) * (vbar - l*np.sum(wbar[-s:]))**2 - 0.5 * np.sum(wbar[-s:]**2) + 0.5*vbar**2 + 0.5*np.linalg.norm(wbar)**2 for s in range(1, len(wbar))]

[15.96330687255092,
 15.504825915418287,
 15.066316113422504,
 14.6363493604468,
 14.215965681138718,
 13.801561139900807,
 13.390493458112788,
 12.9833143779046,
 12.578943503849054,
 12.178479132870091,
 11.779900234079303,
 11.382635000899374,
 11.006362206139862,
 10.630151237351708,
 10.257561938181674,
 9.892809502864083,
 9.52897151506781,
 9.175698318517885,
 8.830203480794388,
 8.489164662090708,
 8.1496810647347,
 7.820966010444799,
 7.492871197383877,
 7.167875566924209,
 6.843571792746637,
 6.52654124316614,
 6.215490331234037,
 5.92482845178829,
 5.655899905006475,
 5.40094423610612,
 5.166102579102638,
 4.9383893462567485,
 4.716735347291014,
 4.528591504922403,
 4.3498933549635765,
 4.172041117566536,
 4.000514900795373,
 3.8487090794658023,
 3.7055415436931654,
 3.5657646406528194,
 3.431155909848158,
 3.2970918328560828,
 3.1662472533280948,
 3.0385341516454503,
 2.915749700785959,
 2.7936370313011665,
 2.6740346760041582,
 2.561091410977234,
 2.4490186088480854,
 2.33

In [71]:
[l**2 / (2*(1-l**2*s)) * (-s*vbar**2 + np.sum(wbar[-s:])**2) + 0.5*np.linalg.norm(wbar)**2 - 0.5*np.sum(wbar[-s:]**2) + l*vbar/(1-l**2*s)*np.sum(wbar[-s:]) - l**2/(1-l**2*s)*np.sum(wbar[-s:])**2 for s in range(1, len(wbar))]

[16.00561305566883,
 15.589086576776026,
 15.191505540732694,
 14.801979590369541,
 14.421496545042256,
 14.046626272460037,
 13.674855605807629,
 13.306709467816129,
 12.941160782871618,
 12.579254017398211,
 12.219068115669394,
 11.860059774901094,
 11.520925270995788,
 11.181782263852213,
 10.846010732427501,
 10.517611234032628,
 10.190014418588316,
 9.87237499610836,
 9.56204709417941,
 9.255880681874713,
 8.951127244015227,
 8.656513185883266,
 8.36242795191535,
 8.071218588157327,
 7.780606436979789,
 7.496820513722373,
 7.218635026231659,
 6.95966027820653,
 6.7211280305167005,
 6.4956991056754445,
 6.289117075068765,
 6.089177405243964,
 5.894874024957041,
 5.731823982398404,
 5.577527725602821,
 5.423986913600283,
 5.276290203029098,
 5.146822887623204,
 5.025298810359574,
 4.906873308420812,
 4.793178215985401,
 4.67996112446906,
 4.569679005606343,
 4.462248757156954,
 4.359314184756349,
 4.256974256681852,
 4.156911335933128,
 4.062912202049193,
 3.9696884651772484,
 3.876

# Multi output

In [76]:
def f(v, w, vbar, wbar, l):
    return 0.5*np.linalg.norm(v - vbar)**2 + 0.5*np.linalg.norm(w - wbar)**2 + l*np.sum(np.tensordot(v, w, axes=0))

In [77]:
def grad_f(v, w, vbar, wbar, l):
    grad_v = v - vbar + l*np.sum(w)
    grad_w = w - wbar + l*np.sum(v)
    return grad_v, grad_w

In [78]:
m = 10
l = 0.04
vbar = np.array([1,2,3,4])
#vbar = np.array([4,3,2,1])
wbar = np.array([-0.2,0.1,0.3,0.4,-0.6,-0.5])

In [79]:
v, w = GD(vbar, wbar, l, n=1000, alpha=0.1)
print(v)
print(w)
print(f(v,w,vbar,wbar,l))

[1. 2. 3. 4.]
[0.00000000e+00 0.00000000e+00 0.00000000e+00 2.48542988e-16
 0.00000000e+00 0.00000000e+00]
0.455


In [80]:
signs_v = np.sign(vbar)
signs_w = np.sign(wbar)
vbar = np.abs(vbar)
wbar = np.abs(wbar)
sorting_permutation_v = np.argsort(vbar)
vbar = vbar[sorting_permutation_v]
sorting_permutation_w = np.argsort(wbar)
wbar = wbar[sorting_permutation_w]

f_best = f(0,0, wbar, vbar, l)
v_best = 0
w_best = 0
for s_w in range(1, len(wbar)+1):
    sum_w = np.sum(wbar[-s_w:])
    w = np.zeros(len(wbar))
    for s_v in range(1, len(vbar)+1):
        sum_v = np.sum(vbar[-s_v:])
        v = np.zeros(len(vbar))
        if 1 - l*np.sqrt(s_v*s_w - 1) >=0:
            v[-1] = ((1 - l**2 * s_v * s_w) * vbar[-1] + l**2 * s_w * sum_v - l * sum_w) / (1 - l**2 * s_v * s_w)
            v[-s_v:-1] = vbar[-s_v:-1] - vbar[-1] + v[-1]
            w[-s_w:] = wbar[-s_w:] - l * np.sum(v)
            if (w >= 0).all() and (v >= 0).all():
                print("Sv = {}, Sw = {}, fval = {}".format(s_v, s_w, f(v,w,vbar,wbar,l)))
                fval = f(v,w,vbar,wbar,l)
                if fval < f_best:
                    v_best = v
                    w_best = w
                    f_best = fval
if f(0, wbar, vbar, wbar, l) < f_best:
    v_best = np.zeros(len(vbar))
    w_best = wbar
    f_best = f(0, wbar, vbar, wbar, l)
if f(vbar, 0, vbar, wbar, l) < f_best:
    v_best = vbar
    w_best = np.zeros(len(wbar))
    f_best = f(vbar, 0, vbar, wbar, l)
    
v_best = signs_v * v_best[sorting_permutation_v]
w_best = signs_w * w_best[sorting_permutation_w]
print(v_best)
print(w_best)
print(f_best)

Sv = 1, Sw = 1, fval = 7.358044871794872
Sv = 2, Sw = 1, fval = 2.903635634028892
Sv = 3, Sw = 1, fval = 0.9260610932475882
Sv = 4, Sw = 1, fval = 0.43487117552334953
Sv = 1, Sw = 2, fval = 7.299911717495988
Sv = 2, Sw = 2, fval = 2.8791304347826094
Sv = 3, Sw = 2, fval = 0.9160500807754443
Sv = 4, Sw = 2, fval = 0.4297082658022692
Sv = 1, Sw = 3, fval = 7.270763665594855
Sv = 2, Sw = 3, fval = 2.871696284329563
Sv = 3, Sw = 3, fval = 0.9151704545454546
Sv = 4, Sw = 3, fval = 0.42970636215334423
Sv = 1, Sw = 4, fval = 7.260716586151369
Sv = 2, Sw = 4, fval = 2.87145056726094
Sv = 1, Sw = 5, fval = 7.259838709677419
[0.98776509 1.98776509 2.98776509 3.98776509]
[-0.          0.          0.          0.00195759 -0.20195759 -0.10195759]
0.42970636215334423


In [3]:
a = np.arange(5)

In [13]:
def prox_Fabian(vbar, wbar, l):
    def f(v, w, vbar, wbar, l):
        return 0.5*np.linalg.norm(v - vbar)**2 + 0.5*np.linalg.norm(w - wbar)**2 + l*np.sum(np.tensordot(v, w, axes=0))
    signs_v = np.sign(vbar)
    signs_w = np.sign(wbar)
    vbar = np.abs(vbar)
    wbar = np.abs(wbar)
    sorting_permutation_v = np.argsort(vbar)
    vbar = vbar[sorting_permutation_v]
    sorting_permutation_w = np.argsort(wbar)
    wbar = wbar[sorting_permutation_w]

    f_best = f(0,0, wbar, vbar, l)
    v_best = 0
    w_best = 0
    for s_w in range(1, len(wbar)+1):
        sum_w = np.sum(wbar[-s_w:])
        w = np.zeros(len(wbar))
        for s_v in range(1, len(vbar)+1):
            sum_v = np.sum(vbar[-s_v:])
            v = np.zeros(len(vbar))
            if 1 - l*np.sqrt(s_v*s_w - 1) >=0:
                v[-1] = ((1 - l**2 * s_v * s_w) * vbar[-1] + l**2 * s_w * sum_v - l * sum_w) / (1 - l**2 * s_v * s_w)
                v[-s_v:-1] = vbar[-s_v:-1] - vbar[-1] + v[-1]
                w[-s_w:] = wbar[-s_w:] - l * np.sum(v)
                if (w >= 0).all() and (v >= 0).all():
                    fval = f(v,w,vbar,wbar,l)
                    if fval < f_best:
                        v_best = v
                        w_best = w
                        f_best = fval
    if f(0, wbar, vbar, wbar, l) < f_best:
        v_best = np.zeros(len(vbar))
        w_best = wbar
        f_best = f(0, wbar, vbar, wbar, l)
    if f(vbar, 0, vbar, wbar, l) < f_best:
        v_best = vbar
        w_best = np.zeros(len(wbar))
        f_best = f(vbar, 0, vbar, wbar, l)

    inverse_permutation_v = np.arange(len(sorting_permutation_v))[np.argsort(sorting_permutation_v)]
    inverse_permutation_w = np.arange(len(sorting_permutation_w))[np.argsort(sorting_permutation_w)]
    v_best = signs_v * v_best[inverse_permutation_v]
    w_best = signs_w * w_best[inverse_permutation_w]
    return v_best, w_best

In [14]:
m = 10
l = 0.04
d = 10
h = 20
o = 5
vbar = np.random.random([o,h])
wbar = np.random.random([h,d])

In [16]:
v = np.zeros(vbar.shape)
w = np.zeros(wbar.shape)
for i in range(h):
    v[:,i], w[i,:] = prox_Fabian(vbar[:,i], wbar[i,:], l)

In [17]:
v

array([[0.34461238, 0.        , 0.64271392, 0.75563978, 0.4415715 ,
        0.        , 0.77418613, 0.60126703, 0.19476648, 0.73632093,
        0.44005435, 0.56652723, 0.51644488, 0.33656185, 0.11915599,
        0.34756709, 0.72409559, 0.14702978, 0.22004075, 0.74702007],
       [0.19505115, 0.        , 0.68325877, 0.69590754, 0.80194254,
        0.30474293, 0.01769261, 0.35535391, 0.47469903, 0.6980308 ,
        0.82136454, 0.22391862, 0.1834579 , 0.13761894, 0.50468139,
        0.45054407, 0.        , 0.18072769, 0.32315578, 0.15218247],
       [0.16902829, 0.20756806, 0.66466713, 0.67890177, 0.59981697,
        0.18747999, 0.18577297, 0.        , 0.42573508, 0.        ,
        0.70490181, 0.83223133, 0.31397509, 0.07318786, 0.12574908,
        0.        , 0.35017157, 0.        , 0.        , 0.80456067],
       [0.32773637, 0.77809329, 0.45285348, 0.43033286, 0.23860197,
        0.52740121, 0.67815734, 0.        , 0.03117438, 0.37468674,
        0.25254777, 0.00762289, 0.78377066, 0

In [22]:
w

array([[0.90035487, 0.00331663, 0.0949772 , 0.19588909, 0.8222864 ,
        0.37176005, 0.18832209, 0.45509397, 0.439078  , 0.31343054],
       [0.39639671, 0.8639344 , 0.93492279, 0.12565388, 0.69892628,
        0.44050034, 0.30439377, 0.33067415, 0.17108408, 0.09644168],
       [0.23867079, 0.22343973, 0.24433771, 0.55483879, 0.54234249,
        0.30821759, 0.52141794, 0.0357295 , 0.        , 0.12560263],
       [0.28151538, 0.8947486 , 0.62359606, 0.07893178, 0.14365322,
        0.12765361, 0.90573882, 0.65899712, 0.46610159, 0.83153785],
       [0.5172404 , 0.93168809, 0.72582251, 0.49180579, 0.21591421,
        0.        , 0.42191345, 0.00503922, 0.2280043 , 0.        ],
       [0.96024621, 0.31955325, 0.514203  , 0.86700278, 0.20839788,
        0.57155828, 0.85853264, 0.94905452, 0.56188667, 0.21288948],
       [0.51047818, 0.75452443, 0.62090091, 0.52960444, 0.58936416,
        0.        , 0.        , 0.04009275, 0.70528681, 0.30877549],
       [0.41172732, 0.        , 0.8576204

In [27]:
v[0,1]

0.0

In [28]:
w[1,:]

array([0.39639671, 0.8639344 , 0.93492279, 0.12565388, 0.69892628,
       0.44050034, 0.30439377, 0.33067415, 0.17108408, 0.09644168])

In [24]:
for i in range(h):
    for j in range(o):
        if v[j,i] == 0 and np.sum(w[i,:]) > 1e-8:
            print(i, j)

1 0
1 3
1 4
2 0
3 2
5 0
5 1
5 3
8 4
9 0
9 2
9 3
9 4
10 3
11 2
12 0
12 3
12 4
17 4
18 1
18 3
19 0
